### ISSUE TITLE
How to getting started? 

### ISSUE THREAD

**Issue by thangngoc89** [bloodyowl/PhenomicFuture#1]
I spent the last 30 minutes to getting started with this branch but no results so far. Could you provide a getting started guide for playing around with the new codebase?

**Comment by MoOx** [comment]
No need for this, we have a current WIP to integrate this directly as a PR in phenomic. Don't waste your time on this yet, just read the code ;)

**Comment by MoOx** [comment]
(btw repo as its current state is broken)

**Comment by thangngoc89** [comment]
kk. I'll wait (and read the code instead)

**Comment by MoOx** [comment]
take a look to phenomic-docs as a starting point ;)
Some files are missing in phenomic-react

**Comment by thangngoc89** [comment]
@bloodyowl I'm amazed by the amount of code you have written sir. So clean and smart.

**Comment by MoOx** [comment]
And that in just in a couple of days. For real. But that came out after lots of discussion.
Anyway @bloodyowl is a machine, not a real human.

**Comment by MoOx** [comment]
after*
